In [54]:
import pandas as pd
low_memory=False

In [55]:
df2018 = pd.read_csv(r'/home/ariana/projetos/analise_dados/dados/DM_ALUNO.CSV', delimiter = "|", usecols=['TP_SEXO', 'NU_IDADE' ,'CO_CURSO','TP_SITUACAO'])

In [56]:
df2018.head()

   CO_CURSO  TP_SEXO  NU_IDADE  TP_SITUACAO
0         1        1        26            2
1         1        2        31            3
2         1        2        30            2
3         1        1        30            3
4         1        2        41            2

In [57]:
df2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12043993 entries, 0 to 12043992
Data columns (total 4 columns):
CO_CURSO       int64
TP_SEXO        int64
NU_IDADE       int64
TP_SITUACAO    int64
dtypes: int64(4)
memory usage: 367.6 MB

In [58]:
df2018.shape
#df2018['CO_CURSO'].value_counts()
df2018.describe()

           CO_CURSO       TP_SEXO      NU_IDADE   TP_SITUACAO
count  1.204399e+07  1.204399e+07  1.204399e+07  1.204399e+07
mean   5.602167e+05  1.442643e+00  2.771838e+01  2.918647e+00
std    8.450108e+05  4.966993e-01  8.569961e+00  1.324609e+00
min    1.000000e+00  1.000000e+00  1.400000e+01  2.000000e+00
25%    5.334700e+04  1.000000e+00  2.100000e+01  2.000000e+00
50%    1.014720e+05  1.000000e+00  2.500000e+01  2.000000e+00
75%    1.167476e+06  2.000000e+00  3.200000e+01  4.000000e+00
max    5.001466e+06  2.000000e+00  1.130000e+02  7.000000e+00

In [59]:
def define_sexo(sex):
    if sex == 1:
        return 'Feminino'
    elif sex == 2:
        return 'Masculino'

df2018['SEXO'] = df2018['TP_SEXO'].map(define_sexo)
df2018.head()

   CO_CURSO  TP_SEXO  NU_IDADE  TP_SITUACAO       SEXO
0         1        1        26            2   Feminino
1         1        2        31            3  Masculino
2         1        2        30            2  Masculino
3         1        1        30            3   Feminino
4         1        2        41            2  Masculino

In [60]:
def define_situacao(sit):
    if sit == 2:
        return 'Cursando'
    if sit == 3:
        return 'Matrícula trancada'
    if sit == 4:
        return 'Desvinculado do curso'
    if sit == 5:
        return 'Transferido para outro curso da mesma IES'
    if sit == 6:
        return 'Formado'    
    elif sit == 7:
        return 'Falecido'

df2018['SITUACAO'] = df2018['TP_SITUACAO'].map(define_situacao)

In [61]:
df2018['IDADE'] = df2018['NU_IDADE']
df2018.head()

,CO_CURSO,TP_SEXO,NU_IDADE,TP_SITUACAO,SEXO,SITUACAO,IDADE
0,1,1,26,2,Feminino,Cursando,26
1,1,2,31,3,Masculino,Matrícula trancada,31
2,1,2,30,2,Masculino,Cursando,30
3,1,1,30,3,Feminino,Matrícula trancada,30
4,1,2,41,2,Masculino,Cursando,41

In [62]:
pd.crosstab(df2018['SITUACAO'],df2018['SEXO'])

SEXO                                       Feminino  Masculino
SITUACAO
Cursando                                    4052436    3134534
Desvinculado do curso                       1169639    1023546
Falecido                                        463        729
Formado                                      765306     499472
Matrícula trancada                           670160     620273
Transferido para outro curso da mesma IES     54799      52636

In [63]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

In [64]:
#situacao_sexo = pd.crosstab(df2018['SITUACAO'],df2018['SEXO'])
#situacao_sexo.plot(kind='bar',width=0.5, color=['red','blue','green','yellow','brown','black'], title='Inserção Mulheres x Homens no Curso de TI' ,grid=False)

In [73]:
dfcurso = pd.read_csv(r'/home/ariana/projetos/analise_dados/dados/curso.csv', usecols=['NO_CURSO','CO_CURSO'])
dfcurso.head()

   CO_CURSO            NO_CURSO
0         1             DIREITO
1         2  CIENCIASECONOMICAS
2         3     ENGENHARIACIVIL
3         6           PEDAGOGIA
4         7       SERVICOSOCIAL

In [74]:
dic = dfcurso.to_dict('split')
dic = dict(dic['data'])
dic

{1: 'DIREITO',
 2: 'CIENCIASECONOMICAS',
 3: 'ENGENHARIACIVIL',
 6: 'PEDAGOGIA',
 7: 'SERVICOSOCIAL',
 8: 'CIENCIASCONTABEIS',
 9: 'AGRONOMIA',
 10: 'ENGENHARIAFLORESTAL',
 1332567: 'ENFERMAGEM',
 12: 'HISTORIA',
 13: 'ADMINISTRACAO',
 15: 'GEOLOGIA',
 16: 'ENGENHARIAELETRICA',
 17: 'ENFERMAGEM',
 19: 'FARMACIA',
 20: 'NUTRICAO',
 21: 'CIENCIASCONTABEIS',
 23: 'PEDAGOGIA',
 24: 'GEOGRAFIA',
 25: 'HISTORIA',
 26: 'MATEMATICA',
 27: 'FISICA',
 29: 'CIENCIASBIOLOGICAS',
 1008205: 'LOGISTICA',
 1179679: 'ENGENHARIACIVIL',
 32: 'CIENCIASBIOLOGICAS',
 34: 'MATEMATICA',
 36: 'CIENCIADACOMPUTACAO',
 37: 'MEDICINAVETERINARIA',
 44: 'ARQUITETURAEURBANISMO',
 1310770: 'CIENCIASCONTABEIS',
 1310772: 'MUSICA',
 87390: 'ESTETICAECOSMETICA',
 1332575: 'PSICOLOGIA',
 1310789: 'LETRASCOMPORTUGUESEESPANHOL',
 1310803: 'ADMINISTRACAOPUBLICA',
 1179735: 'ENGENHARIACIVIL',
 1441881: 'CIENCIASCONTABEIS',
 1179738: 'FARMACIA',
 1179742: 'ENGENHARIADEPRODUCAO',
 1267045: 'CIENCIASBIOLOGICAS',
 1419964: 'GESTAOFINANCEIRA',
 116: 'GEOLOGIA',
 1419966: 'PROCESSOSGERENCIAIS',
 1179766: 'GESTAODERECURSOSHUMANOS',
 119: 'ESTATISTICA',
 1310841: 'DESIGNDIGITAL',
 122: 'CIENCIASECONOMICAS',
 126: 'SERVICOSOCIAL',
 127: 'CIENCIADACOMPUTACAO',
 128: 'RELAC\xd5ESINTERNACIONAIS',
 1156602: 'ENGENHARIACIVIL',
 1179778: 'LETRAS-LINGUAPORTUGUESA',
 132: 'ARQUITETURAEURBANISMO',
 133: 'MUSICA',
 134: 'EDUCACAOARTISTICA',
 135: 'AGRONOMIA',
 136: 'ENGENHARIACIVIL',
 137: 'ENGENHARIAELETRICA',
 138: 'ENGENHARIAMECANICA',
 139: 'ENGENHARIAFLORESTAL',
 140: 'MEDICINA',
 141: 'ODONTOLOGIA',
 142: 'EDUCACAOFISICA',
 143: 'ENFERMAGEM',
 144: 'NUTRICAO',
 145: 'ADMINISTRACAO',
 146: 'BIBLIOTECONOMIA',
 148: 'DIREITO',
 149: 'CIENCIASCONTABEIS',
 150: 'PEDAGOGIA',
 151: 'ARTESPLASTICAS',
 156: 'CIENCIAPOLITICA',
 157: 'ARQUIVOLOGIA',
 158: 'FISICA',
 159: 'QUIMICA',
 160: 'CIENCIASBIOLOGICAS',
 161: 'MATEMATICA',
 162: 'LETRAS-PORTUGUES',
 163: 'PEDAGOGIA',
 164: 'EDUCACAOARTISTICA',
 165: 'DIREITO',
 166: 'LETRAS-ESPANHOL',
 167: 'CIENCIASCONTABEIS',
 1441975: 'BIGDATANOAGRONEGOCIO',
 1441998: 'SISTEMASDEINFORMACAO',
 1442001: 'GESTAODAPRODUCAOINDUSTRIAL',
 1442002: 'CIENCIASBIOLOGICAS',
 1442003: 'MATEMATICA',
 1442006: 'LETRAS-INGLES',
 1442008: 'CIENCIASBIOLOGICAS',
 1442009: 'MATEMATICA',
 1442010: 'GEOGRAFIA',
 1179867: 'PUBLICIDADEEPROPAGANDA',
 1442014: 'GEOGRAFIA',
 1179871: 'ENGENHARIADEPRODUCAO',
 1442016: 'GEOGRAFIA',
 1179874: 'ADMINISTRACAOPUBLICA',
 1442019: 'PEDAGOGIA',
 1442020: 'MATEMATICA',
 1179877: 'MATEMATICA',
 1179878: 'QUIMICA',
 1442023: 'PEDAGOGIA',
 1442024: 'MATEMATICA',
 1442025: 'GEOGRAFIA',
 1442026: 'PEDAGOGIA',
 1442027: 'MATEMATICA',
 1442028: 'HISTORIA',
 1442029: 'CIENCIASBIOLOGICAS',
 1442030: 'GEOGRAFIA',
 1442031: 'PEDAGOGIA',
 1179903: 'CIENCIAS:BIOLOGIA,FISICAEQUIMICA',
 1442052: 'FISIOTERAPIA',
 48011: 'ADMINISTRACAO',
 294: 'ENGENHARIACIVIL',
 295: 'ENGENHARIAQUIMICA',
 297: 'MATEMATICA',
 299: 'QUIMICAINDUSTRIAL',
 302: 'ENFERMAGEM',
 303: 'MEDICINA',
 304: 'ODONTOLOGIA',
 306: 'CIENCIASCONTABEIS',
 308: 'DIREITO',
 1442101: 'COMERCIOEXTERIOR',
 310: 'GEOGRAFIA',
 311: 'HISTORIA',
 1442106: 'SOM,IMAGEMEMOVIMENTO',
 315: 'PEDAGOGIA',
 317: 'CIENCIADACOMPUTACAO',
 318: 'CIENCIASSOCIAIS',
 319: 'ENGENHARIAAGRONOMICA',
 1179968: 'INTERDISCIPLINAREMCIENCIASNATURAIS',
 321: 'MATEMATICA',
 322: 'QUIMICA',
 1179972: 'PROCESSOSGERENCIAIS',
 326: 'FILOSOFIA',
 327: 'CIENCIASBIOLOGICAS',
 328: 'GEOGRAFIA',
 1179977: 'DIREITO',
 1442122: 'GASTRONOMIA',
 1442123: 'TERAPIAOCUPACIONAL',
 1442124: 'ENGENHARIACIVIL',
 1179981: 'HOTELARIA',
 1179982: 'ENGENHARIAMECANICA',
 1442128: 'EDUCACAOFISICA',
 1442130: 'PEDAGOGIA',
 1442132: 'PEDAGOGIA',
 1442133: 'PEDAGOGIA',
 1311074: 'ADMINISTRACAO',
 1180003: 'ENGENHARIADEPRODUCAO',
 1442157: 'SEGUNDALICENCIATURAEMPEDAGOGIA',
 1442158: 'FORMACAOPEDAGOGICAPARAPORTADORESDEENSINOSUPERIOR',
 1442159: 'GESTAOAMBIENTAL',
 1311089: 'PEDAGOGIA',
 1442163: 'MUSICA',
 1442164: 'GESTAOCOMERCIAL',
 1442165: 'GESTAODAQUALIDADE',
 376: 'DIREITO',
 377: 'SERVICOSOCIAL',
 378: 'CIENCIASECONOMICAS',
 379: 'MATEMATICA',
 380: 'FILOSOFIA',
 381: 'PEDAGOGIA',
 382: 'QUIMICA',
 383: 'ENGENHARIACIVIL',
 385: 'ENGENHARIAFLORESTAL',
 386: 'ENGENHARIADEPESCA',
 388: 'CIENCIASCONTABEIS',
 389: 'MEDICINA',
 390: 'FARMACIA',
 391: 'ODONTOLOGIA',
 392: 'ADMINISTRACAO',
 393: 'BIBLIOTECONOMIA',
 394: 'CIENCIASNATURAIS',
 395: 'COMUNICACAOSOCIAL-JORNALISMO',
 396: 'EDUCACAOFISICA',
 397: 'FISICA',
 398: 'CIENCIASBIOLOGICAS',
 399: 'AGRONOMIA',
 400: 'ESTATISTICA',
 401: 'GEOLOGIA',
 402: 'HISTORIA',
 403: 'GEOGRAFIA',
 407: 'CIENCIASSOCIAIS',
 1180085: 'GESTAOFINANCEIRA',
 1180086: 'ENGENHARIACIVIL',
 1180090: 'MARKETING',
 1180101: 'ENGENHARIAAMBIENTALESANITARIA',
 1180102: 'GESTAODAPRODUCAOINDUSTRIAL',
 1180109: 'LOGISTICA',
 1180122: 'ENGENHARIAQUIMICA',
 1180126: 'DIREITO',
 1180128: 'ENFERMAGEM',
 1442275: 'GESTAOFINANCEIRA',
 484: 'MEDICINA',
 485: 'ODONTOLOGIA',
 486: 'ENFERMAGEM',
 487: 'EDUCACAOFISICA',
 488: 'NUTRICAO',
 1442281: 'PROCESSOSGERENCIAIS',
 490: 'CIENCIASCONTABEIS',
 491: 'DIREITO',
 492: 'CIENCIASECONOMICAS',
 1442285: 'ENGENHARIADEPRODUCAO',
 494: 'HISTORIA',
 495: 'GEOGRAFIA',
 496: 'FILOSOFIA',
 497: 'SERVICOSOCIAL',
 498: 'CIENCIASSOCIAIS',
 499: 'ENGENHARIACARTOGRAFICAEDEAGRIMENSURA',
 1442292: 'FISIOTERAPIA',
 501: 'CIENCIASCONTABEIS',
 502: 'CIENCIASECONOMICAS',
 504: 'MEDICINAVETERINARIA',
 508: 'ENGENHARIAAGRONOMICA',
 512: 'ENGENHARIACIVIL',
 513: 'CIENCIADACOMPUTACAO',
 516: 'FARMACIA',
 517: 'ARQUITETURAEURBANISMO',
 518: 'FISICA',
 519: 'QUIMICA',
 520: 'MATEMATICA',
 525: 'CIENCIASBIOLOGICAS',
 1180192: 'ARQUITETURAEURBANISMO',
 1180199: 'ADMINISTRACAO',
 1180207: 'CIENCIASBIOLOGICAS',
 1180209: 'LETRAS',
 1180222: 'GESTAODERECURSOSHUMANOS',
 1180223: 'GESTAOPUBLICA',
 1180225: 'CIENCIASCONTABEIS',
 1180227: 'ADMINISTRACAO',
 1420044: 'TURISMO',
 586: 'ENGENHARIACIVIL',
 587: 'ENGENHARIADEMINAS',
 588: 'ENGENHARIAGEOLOGICA',
 589: 'ENGENHARIAMETALURGICA',
 590: 'FARMACIA',
 591: 'NUTRICAO',
 592: 'HISTORIA',
 593: 'LETRAS',
 594: 'CIENCIADACOMPUTACAO',
 595: 'FILOSOFIA',
 596: 'DIREITO',
 1442393: 'GEOGRAFIA',
 1442394: 'CIENCIASSOCIAIS',
 1180251: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1180252: 'ENGENHARIADEPRODUCAO',
 1180253: 'PSICOLOGIA',
 614: 'CIENCIADACOMPUTACAO',
 615: 'ENGENHARIACIVIL',
 616: 'ENGENHARIADEMATERIAIS',
 619: 'ENGENHARIAQUIMICA',
 621: 'CIENCIASBIOLOGICAS',
 622: 'ESTATISTICA',
 623: 'FISICA',
 624: 'MATEMATICA',
 626: 'ENFERMAGEM',
 627: 'FISIOTERAPIA',
 628: 'TERAPIAOCUPACIONAL',
 630: 'CIENCIASSOCIAIS',
 631: 'ENGENHARIADECOMPUTACAO',
 632: 'ENGENHARIAAGRONOMICA',
 634: 'BIBLIOTECONOMIAECIENCIADAINFORMACAO',
 635: 'EDUCACAOFISICA',
 637: 'MATEMATICA',
 639: 'IMAGEMESOM',
 1180291: 'JOGOSDIGITAIS',
 1180296: 'RADIOLOGIA',
 1180297: 'PEDAGOGIA',
 1160984: 'ENGENHARIAELETRICA',
 1180318: 'MEDICINA',
 1049248: 'GESTAODAPRODUCAOINDUSTRIAL',
 1180321: 'GESTAODERECURSOSHUMANOS',
 682: 'ENGENHARIADEAGRIMENSURAECARTOGRAFICA',
 683: 'ADMINISTRACAO',
 684: 'CIENCIASBIOLOGICAS',
 685: 'AGRONOMIA',
 686: 'CIENCIASECONOMICAS',
 687: 'EDUCACAOFISICA',
 688: 'ECONOMIADOMESTICA',
 689: 'ENGENHARIACIVIL',
 691: 'ENGENHARIADEALIMENTOS',
 692: 'ENGENHARIAFLORESTAL',
 694: 'FISICA',
 695: 'MEDICINAVETERINARIA',
 696: 'MATEMATICA',
 697: 'PEDAGOGIA',
 698: 'NUTRICAO',
 699: 'COOPERATIVISMO',
 700: 'QUIMICA',
 701: 'ZOOTECNIA',
 703: 'CIENCIADACOMPUTACAO',
 704: 'ARQUITETURAEURBANISMO',
 705: 'DIREITO',
 1311443: 'ADMINISTRACAO',
 1311445: 'CIENCIASCONTABEIS',
 1442524: 'PEDAGOGIA',
 1311461: 'ENGENHARIADEPRODUCAO',
 1311462: 'ENGENHARIACIVIL',
 1311466: 'LOGISTICA',
 1180397: 'GESTAODAQUALIDADE',
 750: 'ARQUITETURAEURBANISMO',
 1442543: 'ENGENHARIAMECANICA',
 1442544: 'ENGENHARIAELETRICA',
 1442545: 'ENGENHARIACIVIL',
 754: 'EDUCACAOFISICA',
 755: 'BIBLIOTECONOMIA',
 1442548: 'CIENCIASCONTABEIS',
 1442549: 'BIOMEDICINA',
 758: 'MEDICINA',
 759: 'FISIOTERAPIA',
 760: 'ODONTOLOGIA',
 761: 'FARMACIA',
 762: 'SERVICOSOCIAL',
 1442555: 'PEDAGOGIA',
 764: 'DIREITO',
 1442557: 'SERVICOSOCIAL',
 766: 'ADMINISTRACAO',
 767: 'CIENCIASCONTABEIS',
 768: 'MATEMATICA',
 769: 'QUIMICA',
 770: 'FISICA',
 771: 'GEOGRAFIA',
 772: 'CIENCIASBIOLOGICAS',
 773: 'PSICOLOGIA',
 774: 'CIENCIASSOCIAIS',
 775: 'HISTORIA',
 1442568: 'HISTORIA',
 777: 'MEDICINAVETERINARIA',
 778: 'CIENCIADACOMPUTACAO',
 779: 'FILOSOFIA',
 780: 'MUSICA',
 781: 'SECRETARIADOEXECUTIVO',
 1442574: 'FOTOGRAFIA',
 21976: 'EDUCACAOFISICA',
 1442580: 'BANCODEDADOS',
 1157934: 'GESTAODERECURSOSHUMANOS',
 1442584: 'DESIGNDEPRODUTO',
 1442586: 'DESIGNGRAFICO',
 1442589: 'DESIGNDEINTERIORES',
 1442590: 'CIENCIASECONOMICAS',
 1442591: 'SERVICOSOCIAL',
 1180450: 'PETROLEOEGAS',
 1442595: 'COMERCIOEXTERIOR',
 1442596: 'EMPREENDEDORISMO',
 1442597: 'GESTAODAQUALIDADE',
 1442598: 'GESTAODESEGURANCAPRIVADA',
 1442599: 'GESTAODEAGRONEGOCIOS',
 1442600: 'GESTAOHOSPITALAR',
 1442601: 'NUTRICAO',
 1442602: 'JOGOSDIGITAIS',
 1442603: 'REDESDECOMPUTADORES',
 1442604: 'ESTETICAECOSMETICA',
 1442606: 'JORNALISMO',
 1179787: 'FARMACIA',
 849: 'FILOSOFIA',
 850: 'PEDAGOGIA',
 855: 'EDUCACAOFISICA',
 856: 'SECRETARIADOEXECUTIVO',
 857: 'DIREITO',
 859: 'SERVICOSOCIAL',
 860: 'MATEMATICA',
 861: 'CIENCIASBIOLOGICAS',
 863: 'ENGENHARIACIVIL',
 864: 'ARQUITETURAEURBANISMO',
 865: 'CIENCIADACOMPUTACAO',
 866: 'PSICOLOGIA',
 867: 'ENFERMAGEM',
 868: 'MEDICINA',
 869: 'ODONTOLOGIA',
 870: 'FISIOTERAPIA',
 872: 'ENGENHARIADACOMPUTACAO',
 65473: 'SISTEMASPARAINTERNET',
 877: 'ADMINISTRACAO',
 881: 'ENGENHARIAELETRICA',
 882: 'CIENCIASCONTABEIS',
 884: 'ENGENHARIAMECANICA',
 885: 'ENGENHARIAQUIMICA',
 886: 'AGRONOMIA',
 888: 'MEDICINAVETERINARIA',
 1180543: 'ODONTOLOGIA',
 1442695: 'GASTRONOMIA',
 1442696: 'GESTAODESPORTIVAEDELAZER',
 1442697: 'PRODUCAOCULTURAL',
 1442698: 'GESTAODAPRODUCAOINDUSTRIAL',
 1442699: 'SEGURANCANOTRABALHO',
 1442700: 'ENGENHARIAELETRICA',
 109378: 'ENGENHARIAAMBIENTAL',
 1442702: 'PUBLICIDADEEPROPAGANDA',
 1442704: 'ENGENHARIACIVIL',
 1442705: 'SECRETARIADO',
 1180566: 'ENGENHARIACIVIL',
 1180567: 'ENGENHARIADEPRODUCAO',
 109380: 'ENGENHARIAAMBIENTAL',
 1442715: 'FISICA',
 1442716: 'GEOGRAFIA',
 1332720: 'MARKETING',
 1136113: 'GESTAODERECURSOSHUMANOS',
 1442732: 'ENGENHARIADEMINAS',
 109384: 'CIENCIASECONOMICAS',
 1310878: 'ENGENHARIACARTOGRAFICAEDEAGRIMENSURA',
 950: 'FILOSOFIA',
 952: 'PSICOLOGIA',
 953: 'FONOAUDIOLOGIA',
 954: 'PEDAGOGIA',
 955: 'HISTORIA',
 1180604: 'GESTAOAMBIENTAL',
 957: 'SERVICOSOCIAL',
 958: 'CIENCIASECONOMICAS',
 959: 'CIENCIASCONTABEIS',
 960: 'ADMINISTRACAO',
 1180609: 'FOTOGRAFIA',
 1180610: 'ENGENHARIAAMBIENTALEENERGIASRENOVAVEIS',
 963: 'DIREITO',
 964: 'ENGENHARIACIVIL',
 965: 'MATEMATICA',
 1180614: 'CIENCIASCONTABEIS',
 1180615: 'PROCESSOSGERENCIAIS',
 968: 'CIENCIADACOMPUTACAO',
 970: 'ENGENHARIAQUIMICA',
 971: 'QUIMICA',
 972: 'CIENCIASBIOLOGICAS',
 1180627: 'QUIMICA-QUIMICAFORENSE',
 1180629: 'DESIGNDEINTERIORES',
 1180630: 'FOTOGRAFIA',
 1049561: 'ADMINISTRACAO',
 1180635: 'GESTAOHOSPITALAR',
 1180644: 'ARQUITETURAEURBANISMO',
 1442792: 'GESTAOCOMERCIAL',
 1442796: 'MARKETING',
 1442803: 'PROCESSOSGERENCIAIS',
 1442804: 'ADMINISTRACAO',
 1442809: 'COMERCIOEXTERIOR',
 1442812: 'ENGENHARIACIVIL',
 1442813: 'CIENCIASCONTABEIS',
 1442814: 'GESTAODERECURSOSHUMANOS',
 1442815: 'GESTAODATECNOLOGIADAINFORMACAO',
 1442816: 'SEGURANCAPUBLICA',
 1442817: 'MARKETING',
 1026: 'MEDICINA',
 1027: 'CIENCIASECONOMICAS',
 1028: 'ADMINISTRACAO',
 1029: 'OCEANOLOGIA',
 1442822: 'HISTORIA',
 1442823: 'LETRAS-PORTUGUESEINGLES',
 1442824: 'SEGUNDALICENCIATURAEMPEDAGOGIA',
 1033: 'GEOGRAFIA',
 1034: 'HISTORIA',
 1035: 'MATEMATICA',
 1036: 'LETRAS-LINGUAPORTUGUESA',
 1037: 'LETRAS-PORTUGUESEFRANCES',
 1038: 'ENGENHARIACIVIL',
 1039: 'ENGENHARIAMECANICA',
 1040: 'ENGENHARIAQUIMICA',
 1041: 'CIENCIASCONTABEIS',
 1042: 'BIBLIOTECONOMIA',
 1043: 'ENFERMAGEM',
 1044: 'ARTESVISUAIS',
 1045: 'ENGENHARIADEALIMENTOS',
 1046: 'LETRAS-PORTUGUESEINGLES',
 1051: 'ENGENHARIADECOMPUTACAO',
 1052: 'LETRAS-PORTUGUESEESPANHOL',
 65712: 'GESTAODERECURSOSHUMANOS',
 1180706: 'GESTAOFINANCEIRA',
 1180707: 'LETRAS-PORTUGUESEINGLES',
 1070598: 'LOGISTICA',
 1330304: 'ENGENHARIACIVIL',
 1180712: 'CIENCIASCONTABEIS',
 1180714: 'PEDAGOGIA',
 1442859: 'GESTAODERECURSOSHUMANOS',
 1442860: 'GESTAOAMBIENTAL',
 1442861: 'PROCESSOSGERENCIAIS',
 1442862: 'COMERCIOEXTERIOR',
 1442863: 'GESTAODAQUALIDADE',
 1442864: 'MARKETING',
 1442865: 'GESTAOCOMERCIAL',
 1442866: 'GESTAOFINANCEIRA',
 1442867: 'ADMINISTRACAO',
 1442868: 'CIENCIASCONTABEIS',
 1442869: 'PEDAGOGIA',
 1049654: 'CIENCIASCONTABEIS',
 1049656: 'ENFERMAGEM',
 1442878: 'ESTETICAECOSMETICA',
 65717: 'DIREITO',
 1442880: 'AGROINDUSTRIA',
 1180737: 'SERVICOSOCIAL',
 1095: 'HISTORIA',
 1098: 'SERVICOSOCIAL',
 1101: 'DIREITO',
 1442894: 'ADMINISTRACAO',
 1103: 'CIENCIASCONTABEIS',
 1104: 'CIENCIASECONOMICAS',
 1105: 'HOTELARIA',
 1107: 'MEDICINA',
 1180756: 'FOTOGRAFIA',
 1109: 'CIENCIASBIOLOGICAS',
 1110: 'CIENCIADACOMPUTACAO',
 1180759: 'FOTOGRAFIA',
 1112: 'MATEMATICA',
 1113: 'DIREITO',
 1442906: 'MATEMATICA',
 1180765: 'SERVICOSOCIAL',
 1180766: 'GESTAODAQUALIDADE',
 1180767: 'SERVICOSOCIAL',
 1180768: 'GESTAODESEGURANCAPRIVADA',
 1121: 'CIENCIASCONTABEIS',
 1180770: 'GESTAODAQUALIDADE',
 1124: 'DIREITO',
 1180773: 'SISTEMASDEINFORMACAO',
 1180775: 'GESTAODAQUALIDADE',
 1180776: 'ADMINISTRACAO',
 1130: 'TURISMO',
 1442923: 'ARTESVISUAIS',
 1442924: 'GEOGRAFIA',
 1442925: 'FILOSOFIA',
 1442926: 'CIENCIASSOCIAIS',
 1442927: 'HISTORIA',
 1180784: 'PRODUCAOAUDIOVISUAL',
 1180785: 'SERVICOSOCIAL',
 1180786: 'BIOMEDICINA',
 1180788: 'SERVICOSOCIAL',
 1180789: 'GESTAODATECNOLOGIADAINFORMACAO',
 1180792: 'BIOMEDICINA',
 1180794: 'SERVICOSOCIAL',
 1180796: 'GESTAODATECNOLOGIADAINFORMACAO',
 1180797: 'RADIOLOGIA',
 1180799: 'GESTAODATECNOLOGIADAINFORMACAO',
 1442949: 'ENGENHARIADEPRODUCAO',
 1180806: 'GESTAOCOMERCIAL',
 1180807: 'BIOMEDICINA',
 1180808: 'ENGENHARIAMECANICA',
 1180809: 'COMERCIOEXTERIOR',
 1180814: 'ENGENHARIACIVIL',
 1180815: 'COMERCIOEXTERIOR',
 1180816: 'CIENCIASBIOLOGICAS',
 1442964: 'CIENCIASCONTABEIS',
 1442965: 'ENGENHARIAAGRONOMICA',
 1442967: 'ADMINISTRACAO',
 1442969: 'PEDAGOGIA',
 1442970: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1442971: 'CIENCIASCONTABEIS',
 1442972: 'COMERCIOEXTERIOR',
 1442973: 'EDUCACAOFISICA',
 1180831: 'JORNALISMO',
 1442976: 'GESTAODAQUALIDADE',
 1180833: 'ARQUITETURAEURBANISMO',
 1442978: 'GESTAOFINANCEIRA',
 1442979: 'LOGISTICA',
 1442980: 'MARKETING',
 1442982: 'PROCESSOSGERENCIAIS',
 1180846: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1442995: 'CIENCIAPOLITICA',
 1442999: 'COZINHACONTEMPORANEA',
 1443000: 'COZINHACONTEMPORANEA',
 1180860: 'EDUCACAOFISICA-ENFASEEMEDUCACAOFISICAESAUDE',
 1180861: 'EDUCACAOFISICA-ENFASEEMESPORTE',
 1222: 'HISTORIA',
 1223: 'FILOSOFIA',
 1224: 'CIENCIASSOCIAIS',
 1225: 'ENFERMAGEM',
 1227: 'NUTRICAO',
 1230: 'DIREITO',
 1232: 'CIENCIASECONOMICAS',
 1233: 'CIENCIASCONTABEIS',
 1237: 'ARQUITETURAEURBANISMO',
 1240: 'GEOLOGIA',
 1242: 'SERVICOSOCIAL',
 109434: 'GESTAOFINANCEIRA',
 1253: 'EDUCACAOFISICA',
 1049833: 'PSICOLOGIA',
 1261: 'SISTEMASDEINFORMACAO',
 22056: 'ARQUITETURAEURBANISMO',
 1443068: 'LOGISTICA',
 1443070: 'COMERCIOEXTERIOR',
 1114325: 'CIENCIASCONTABEIS',
 1180933: 'ENGENHARIACIVIL',
 1312009: 'PRODUCAOFONOGRAFICA',
 1158018: 'ENFERMAGEM',
 1180947: 'DESIGNDEINTERIORES',
 1312023: 'CIENCIADACOMPUTACAO',
 1331222: 'ENGENHARIACIVIL',
 1179866: 'ENGENHARIADEPRODUCAO',
 1312: 'ADMINISTRACAO',
 1313: 'CIENCIASCONTABEIS',
 1314: 'CIENCIASECONOMICAS',
 1315: 'DIREITO',
 1049893: 'ADMINISTRACAO',
 1318: 'ENGENHARIAELETRICA',
 1319: 'ENGENHARIAMECANICA',
 1049896: 'FARMACIA',
 1321: 'FILOSOFIA',
 1322: 'FISIOTERAPIA',
 1325: 'LETRAS-LINGUAPORTUGUESA',
 1326: 'PEDAGOGIA',
 1327: 'PSICOLOGIA',
 1179870: 'BIOMEDICINA',
 1443138: 'ENGENHARIAELETRICA',
 1354636: 'CIENCIASCONTABEIS',
 306061: 'QUIMICA',
 1070648: 'PSICOLOGIA',
 122252: 'GEOGRAFIA',
 1310949: 'GESTAODERECURSOSHUMANOS',
 1443169: 'MEDICINAVETERINARIA',
 1181029: 'DESIGNDEINTERIORES',
 1181030: 'DESIGNDEINTERIORES',
 1181034: 'DESIGNDEINTERIORES',
 1443179: 'DESIGNGRAFICO',
 1181036: 'DESIGNDEINTERIORES',
 1181037: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1443183: 'NUTRICAO',
 1443184: 'PEDAGOGIA',
 1181042: 'MATEMATICA',
 1332798: 'ALIMENTOS',
 1443190: 'BIOMEDICINA',
 1443191: 'CIENCIASCONTABEIS',
 1443192: 'PUBLICIDADEEPROPAGANDA',
 1443193: 'FISIOTERAPIA',
 1443194: 'NUTRICAO',
 1443195: 'PEDAGOGIA',
 1181052: 'HISTORIA',
 1181053: 'HISTORIA',
 1181054: 'PEDAGOGIA',
 1443199: 'AGRONOMIA',
 1310955: 'SISTEMASDEINFORMACAO',
 1443205: 'ENGENHARIAQUIMICA',
 1443206: 'ENGENHARIADECOMPUTACAO',
 1443207: 'ADMINISTRACAO',
 1443208: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1428: 'MATEMATICA',
 1429: 'QUIMICA',
 1430: 'CIENCIASBIOLOGICAS',
 1431: 'CIENCIASECONOMICAS',
 1433: 'AGRONOMIA',
 1434: 'LETRAS',
 1435: 'PEDAGOGIA',
 1436: 'DIREITO',
 1438: 'EDUCACAOFISICA',
 1439: 'MEDICINA',
 1440: 'MEDICINAVETERINARIA',
 1441: 'ODONTOLOGIA',
 1443: 'CIENCIASCONTABEIS',
 1444: 'MUSICA',
 1445: 'GEOGRAFIA',
 1446: 'HISTORIA',
 1181095: 'ADMINISTRACAO',
 1448: 'ENGENHARIACIVIL',
 1449: 'ENGENHARIAELETRICA',
 1450: 'ENGENHARIAMECANICA',
 1451: 'ENGENHARIAQUIMICA',
 1452: 'CIENCIADACOMPUTACAO',
 1453: 'FILOSOFIA',
 1454: 'FISICA',
 1181115: 'CIENCIADACOMPUTACAO',
 1181116: 'ZOOTECNIA',
 1050049: 'CIENCIASCONTABEIS',
 1050050: 'ADMINISTRACAO',
 1050051: 'FARMACIA',
 1050053: 'SISTEMASDEINFORMACAO',
 1181129: 'ALIMENTOS',
 1181130: 'LATICINIOS',
 1181132: 'FISICA',
 1312211: 'MATEMATICA',
 1443285: 'PROCESSOSGERENCIAIS',
 1443291: 'GESTAOFINANCEIRA',
 1312227: 'HISTORIA',
 394725: 'ARTESVISUAIS',
 1511: 'ENGENHARIACIVIL',
 1512: 'ENGENHARIAELETRICA',
 1513: 'FILOSOFIA',
 1515: 'PEDAGOGIA',
 1516: 'PSICOLOGIA',
 1517: 'ADMINISTRACAO',
 1518: 'MEDICINA',
 1523: 'CIENCIASCONTABEIS',
 1526: 'SERVICOSOCIAL',
 1289129: 'TEATRO',
 1530: 'TEOLOGIA',
 1531: 'DIREITO',
 1443325: 'FOTOGRAFIA',
 1534: 'ARQUITETURAEURBANISMO',
 1536: 'ENGENHARIAELETRONICA',
 1443332: 'DESIGNDEINTERIORES',
 1443335: 'ENGENHARIAAMBIENTALESANITARIA',
 1443337: 'ADMINISTRACAO',
 1443338: 'RELAC\xd5ESINTERNACIONAIS',
 1443339: 'ANALISEEDESENVOLVIMENTODESISTEMAS',
 1181199: 'ARQUITETURAEURBANISMO',
 1181208: 'ENGENHARIAELETRICA',
 1181214: 'PEDAGOGIA',
 1181216: 'GESTAODERECURSOSHUMANOS',
 1181217: 'ARQUITETURAEURBANISMO',
 1181219: 'NUTRICAO',
 1181226: 'ENGENHARIADEPRODUCAO',
 1181228: 'LOGISTICA',
 1181231: 'EDUCACAOFISICA',
 1181233: 'EDUCACAOFISICA',
 1181234: 'LOGISTICA',
 1181235: 'EDUCACAOFISICA',
 1181236: 'LOGISTICA',
 1443381: 'DESIGNDEMODA',
 1181238: 'EDUCACAOFISICA',
 1312315: 'DESIGNDEMODA',
 1312322: 'ALIMENTOS',
 1443399: 'CIENCIASCONTABEIS',
 1443400: 'DESIGNDEMODA',
 1443401: 'CIENCIASBIOLOGICAS',
 1443402: 'ESTETICAECOSMETICA',
 1443403: 'JORNALISMO',
 1181260: 'ARQUITETURAEURBANISMO',
 1181261: 'ENGENHARIAELETRICA',
 1443406: 'CIENCIASECONOMICAS',
 1181263: 'GESTAOEMPRESARIAL',
 1443408: 'BIOMEDICINA',
 1443409: 'NUTRICAO',
 1443412: 'CIENCIASBIOLOGICAS',
 1443413: 'CIENCIASECONOMICAS',
 1443414: 'CIENCIASECONOMICAS',
 1443415: 'RELAC\xd5ESINTERNACIONAIS',
 1624: 'CIENCIASBIOLOGICAS',
 1443417: 'GESTAOCOMERCIAL',
 1626: 'TURISMO',
 1627: 'ENFERMAGEM',
 1628: 'FISIOTERAPIA',
 1629: 'MEDICINA',
 1630: 'NUTRICAO',
 1631: 'ODONTOLOGIA',
 1632: 'TERAPIAOCUPACIONAL',
 1634: 'ARQUITETURAEURBANISMO',
 1635: 'ENGENHARIACIVIL',
 1636: 'BIBLIOTECONOMIA',
 1637: 'MATEMATICA',
 1638: 'CIENCIASSOCIAIS',
 1641: 'EDUCACAOFISICA',
 1642: 'DIREITO',
 1643: 'FILOSOFIA',
 1644: 'FONOAUDIOLOGIA',
 1646: 'HISTORIA',
 1648: 'PEDAGOGIA',
 1650: 'SERVICOSOCIAL',
 1651: 'TEOLOGIA',
 1652: 'CIENCIASECONOMICAS',
 1653: 'CIENCIASCONTABEIS',
 1654: 'ADMINISTRACAO',
 1050233: 'GESTAOAMBIENTAL',
 1050234: 'COMERCIOEXTERIOR',
 1659: 'QUIMICA',
 1660: 'ENGENHARIADECOMPUTACAO',
 1312385: 'ADMINISTRACAO',
 1181315: 'LOGISTICA',
 1181317: 'GESTAODERECURSOSHUMANOS',
 1181318: 'EDUCACAOFISICA',
 1312398: 'PEDAGOGIA',

In [75]:
def define_curso(codigo):
  return dic[codigo]
   
df2018['CURSO'] = df2018['CO_CURSO'].map(define_curso)
df2018.head()
#df_novo = df2018.loc[df2018.CO_CURSO==1442705]
#df_novo.info()
#df2018['CO_CURSO'].replace(dic, inplace=True)
#df2018.head()

,CO_CURSO,TP_SEXO,NU_IDADE,TP_SITUACAO,SEXO,SITUACAO,IDADE,CURSO
0,1,1,26,2,Feminino,Cursando,26,DIREITO
1,1,2,31,3,Masculino,Matrícula trancada,31,DIREITO
2,1,2,30,2,Masculino,Cursando,30,DIREITO
3,1,1,30,3,Feminino,Matrícula trancada,30,DIREITO
4,1,2,41,2,Masculino,Cursando,41,DIREITO

In [82]:
data = (df2018.loc[df2018['CURSO'].isin(['INFORMATICA' , 'COMPUTACAO', 'ANALISEEDESENVOLVIMENTODESISTEMAS', 'TECNOLOGIADAINFORMACAO'])])
data

,CO_CURSO,TP_SEXO,NU_IDADE,TP_SITUACAO,SEXO,SITUACAO,IDADE,CURSO
11556,41687,2,38,3,Masculino,Matrícula trancada,38,INFORMATICA
11557,41687,2,30,6,Masculino,Formado,30,INFORMATICA
11558,41687,1,27,3,Feminino,Matrícula trancada,27,INFORMATICA
11559,41687,2,44,6,Masculino,Formado,44,INFORMATICA
11560,41687,2,28,6,Masculino,Formado,28,INFORMATICA
11561,41687,2,36,6,Masculino,Formado,36,INFORMATICA
49437,18032,2,30,4,Masculino,Desvinculado do curso,30,COMPUTACAO
49438,18032,2,27,2,Masculino,Cursando,27,COMPUTACAO
49439,18032,2,34,4,Masculino,Desvinculado do curso,34,COMPUTACAO
49440,18032,2,47,3,Masculino,Matrícula trancada,47,COMPUTACAO
49441,18032,2,34,3,Masculino,Matrícula trancada,34,COMPUTACAO
49442,18032,2,29,2,Masculino,Cursando,29,COMPUTACAO
49443,18032,2,31,3,Masculino,Matrícula trancada,31,COMPUTACAO
49444,18032,2,29,2,Masculino,Cursando,29,COMPUTACAO
49445,18032,2,27,6,Masculino,Formado,27,COMPUTACAO
49446,18032,2,29,4,Masculino,Desvinculado do curso,29,COMPUTACAO
49447,18032,2,27,2,Masculino,Cursando,27,COMPUTACAO
49448,18032,1,31,4,Feminino,Desvinculado do curso,31,COMPUTACAO
49449,18032,2,36,4,Masculino,Desvinculado do curso,36,COMPUTACAO
49450,18032,2,35,2,Masculino,Cursando,35,COMPUTACAO
49451,18032,2,32,4,Masculino,Desvinculado do curso,32,COMPUTACAO
49452,18032,2,29,2,Masculino,Cursando,29,COMPUTACAO
49453,18032,2,35,2,Masculino,Cursando,35,COMPUTACAO
49454,18032,1,32,2,Feminino,Cursando,32,COMPUTACAO
49455,18032,2,48,3,Masculino,Matrícula trancada,48,COMPUTACAO
49456,18032,2,31,4,Masculino,Desvinculado do curso,31,COMPUTACAO
49457,18032,2,36,6,Masculino,Formado,36,COMPUTACAO
49458,18032,2,40,2,Masculino,Cursando,40,COMPUTACAO
49459,18032,2,30,4,Masculino,Desvinculado do curso,30,COMPUTACAO
49460,18032,1,30,3,Feminino,Matrícula trancada,30,COMPUTACAO
...,...,...,...,...,...,...,...,...
12043841,1458085,2,20,2,Masculino,Cursando,20,ANALISEEDESENVOLVIMENTODESISTEMAS
12043842,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043843,1458085,2,19,2,Masculino,Cursando,19,ANALISEEDESENVOLVIMENTODESISTEMAS
12043844,1458085,2,30,2,Masculino,Cursando,30,ANALISEEDESENVOLVIMENTODESISTEMAS
12043845,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043846,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043847,1458085,2,27,2,Masculino,Cursando,27,ANALISEEDESENVOLVIMENTODESISTEMAS
12043848,1458085,2,23,2,Masculino,Cursando,23,ANALISEEDESENVOLVIMENTODESISTEMAS
12043849,1458085,2,24,2,Masculino,Cursando,24,ANALISEEDESENVOLVIMENTODESISTEMAS
12043850,1458085,2,21,2,Masculino,Cursando,21,ANALISEEDESENVOLVIMENTODESISTEMAS
12043851,1458085,2,21,2,Masculino,Cursando,21,ANALISEEDESENVOLVIMENTODESISTEMAS
12043852,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043853,1458085,1,18,2,Feminino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043854,1458085,2,20,2,Masculino,Cursando,20,ANALISEEDESENVOLVIMENTODESISTEMAS
12043855,1458085,2,20,2,Masculino,Cursando,20,ANALISEEDESENVOLVIMENTODESISTEMAS
12043856,1458085,2,21,2,Masculino,Cursando,21,ANALISEEDESENVOLVIMENTODESISTEMAS
12043857,1458085,2,19,2,Masculino,Cursando,19,ANALISEEDESENVOLVIMENTODESISTEMAS
12043858,1458085,2,19,2,Masculino,Cursando,19,ANALISEEDESENVOLVIMENTODESISTEMAS
12043859,1458085,2,21,2,Masculino,Cursando,21,ANALISEEDESENVOLVIMENTODESISTEMAS
12043860,1458085,2,20,2,Masculino,Cursando,20,ANALISEEDESENVOLVIMENTODESISTEMAS
12043861,1458085,2,19,2,Masculino,Cursando,19,ANALISEEDESENVOLVIMENTODESISTEMAS
12043862,1458085,2,19,2,Masculino,Cursando,19,ANALISEEDESENVOLVIMENTODESISTEMAS
12043863,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043864,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043865,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043866,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043867,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043868,1458085,2,18,2,Masculino,Cursando,18,ANALISEEDESENVOLVIMENTODESISTEMAS
12043869,1458085,2,22,4,Masculino,Desvinculado do curso,22,ANALISEEDESENVOLVIMENTODESISTEMAS
12043870,1458085,2,20,4,Masculino,Desvinculado do curso,20,ANALISEEDESENVOLVIMENTODESISTEMAS

In [83]:
data.isnull().sum()

CO_CURSO       0
TP_SEXO        0
NU_IDADE       0
TP_SITUACAO    0
SEXO           0
SITUACAO       0
IDADE          0
CURSO          0
dtype: int64

In [84]:
data.head()

,CO_CURSO,TP_SEXO,NU_IDADE,TP_SITUACAO,SEXO,SITUACAO,IDADE,CURSO
11556,41687,2,38,3,Masculino,Matrícula trancada,38,INFORMATICA
11557,41687,2,30,6,Masculino,Formado,30,INFORMATICA
11558,41687,1,27,3,Feminino,Matrícula trancada,27,INFORMATICA
11559,41687,2,44,6,Masculino,Formado,44,INFORMATICA
11560,41687,2,28,6,Masculino,Formado,28,INFORMATICA

In [85]:
data.nunique()

CO_CURSO       671
TP_SEXO          2
NU_IDADE        67
TP_SITUACAO      6
SEXO             2
SITUACAO         6
IDADE           67
CURSO            4
dtype: int64

In [86]:
data['CURSO'].unique()

array(['INFORMATICA', 'COMPUTACAO', 'ANALISEEDESENVOLVIMENTODESISTEMAS',
       'TECNOLOGIADAINFORMACAO'], dtype=object)

In [87]:
data['CURSO'].value_counts()

ANALISEEDESENVOLVIMENTODESISTEMAS    165271
COMPUTACAO                             7975
INFORMATICA                            6302
TECNOLOGIADAINFORMACAO                 1233
Name: CURSO, dtype: int64

In [88]:
pd.crosstab(data['CURSO'],data['SEXO'])

SEXO                               Feminino  Masculino
CURSO
ANALISEEDESENVOLVIMENTODESISTEMAS     22837     142434
COMPUTACAO                             2386       5589
INFORMATICA                            1892       4410
TECNOLOGIADAINFORMACAO                  132       1101

In [89]:
pd.crosstab(data['SITUACAO'],data['SEXO'])

SEXO                                       Feminino  Masculino
SITUACAO
Cursando                                      14549      81591
Desvinculado do curso                          6810      37144
Falecido                                          3         16
Formado                                        2220      13378
Matrícula trancada                             3417      20229
Transferido para outro curso da mesma IES       248       1176

In [90]:
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

In [92]:
curso_sexo = pd.crosstab(data['CURSO'],data['SEXO'])
curso_sexo.plot(kind='bar',width=0.5, color=['red','blue'], title='Inserção Mulheres x Homens no Curso de TI')

Error in callback <function post_execute at 0x7ff7c172d398> (for post_execute):

ValueError: matplotlib display text must have all code points < 128 or use Unicode strings

ValueError: matplotlib display text must have all code points < 128 or use Unicode strings